export const ABILITY_IMPLEMENTATION_KEYS = [
  "main_roll_low_becomes_four",
  "trip_on_shared_stop",
  "trip_passing_racer",
  "corner_based_main_move_modifier",
  "move_passed_racer_back_two",
  "cheer_last_place_then_self",
  "same_space_main_move_plus_one",
  "copy_lead_racer_power",
  "grant_reroll_move_on_use",
  "duel_on_shared_space",
  "draft_temp_power_before_race",
  "warp_swap_instead_main_move",
  "predict_roll_extra_turn",
  "others_main_move_minus_one",
  "hare_fast_unless_alone_lead",
  "move_when_turn_ends_near_start",
  "prevent_sharing_space_push_behind",
  "warp_racer_to_self_before_main",
  "skip_others_one_roll_move_self",
  "move_two_before_other_six",
  "skip_occupied_spaces_while_moving",
  "main_move_fixed_five_optional",
  "gain_point_if_alone_last_before_main",
  "reroll_main_move_up_to_two",
  "predict_winner_finish_second",
  "eliminate_single_shared_racer",
  "pull_all_then_bonus_per_guest",
  "optional_double_roll_then_trip",
  "move_two_on_pair_stop",
  "move_one_on_other_power",
  "points_then_six_warp_start",
  "take_next_turn_on_roll_one",
  "others_need_exact_finish",
  "follow_same_space_mover",
  "warp_to_exactly_two_before_main",
  "copy_previous_winner_before_race",
] as const;

export type AbilityImplementationKey = (typeof ABILITY_IMPLEMENTATION_KEYS)[number];

export const PHASE_TWO_ACTIVE_ABILITY_KEYS = [
  "main_roll_low_becomes_four",
  "trip_passing_racer",
  "same_space_main_move_plus_one",
  "others_main_move_minus_one",
  "hare_fast_unless_alone_lead",
  "main_move_fixed_five_optional",
  "reroll_main_move_up_to_two",
  "optional_double_roll_then_trip",
] as const satisfies readonly AbilityImplementationKey[];
