import type { Athlete } from "./types";

type AthleteData = Omit<Athlete, "id" | "sourceKey" | "artPrompt">;

const STANDARD_ATHLETE_DATA = [
  {
    standardName: "Alchemist",
    displayName: "炼金师",
    type: "mainMove",
    abilityText: "main move 掷出 1 或 2 时，可以改为移动 4 格。",
    abilityHooks: ["afterRoll", "modifyMainMove"],
    implementationKey: "main_roll_low_becomes_four",
    tags: ["standard", "phase-2-active", "main-move"],
  },
  {
    standardName: "Baba Yaga",
    displayName: "芭芭雅嘎",
    type: "reaction",
    abilityText: "任意选手停在她的格子，或她停在任意选手格子时，使对方 trip。",
    abilityHooks: ["onSharedStop"],
    implementationKey: "trip_on_shared_stop",
    tags: ["standard", "trip", "sharing"],
  },
  {
    standardName: "Banana",
    displayName: "香蕉",
    type: "reaction",
    abilityText: "任意选手 passing 她时，使该选手 trip。",
    abilityHooks: ["onPass"],
    implementationKey: "trip_passing_racer",
    tags: ["standard", "phase-2-active", "trip", "passing"],
  },
  {
    standardName: "Blimp",
    displayName: "飞艇",
    type: "mainMove",
    abilityText: "回合开始时若在第二个弯角前，main move +3；若在该弯角或之后，main move -1。",
    abilityHooks: ["beforeMainMove", "modifyMainMove"],
    implementationKey: "corner_based_main_move_modifier",
    tags: ["standard", "track-position", "main-move"],
  },
  {
    standardName: "Centaur",
    displayName: "半人马",
    type: "movement",
    abilityText: "当他 passing 一名选手时，被超过者 move -2，最低不低于起点。",
    abilityHooks: ["onPass"],
    implementationKey: "move_passed_racer_back_two",
    tags: ["standard", "passing", "movement"],
  },
  {
    standardName: "Cheerleader",
    displayName: "啦啦队长",
    type: "movement",
    abilityText: "main move 前可以让 last place 选手 move 2；若这样做，自己再 move 1。",
    abilityHooks: ["beforeMainMove"],
    implementationKey: "cheer_last_place_then_self",
    tags: ["standard", "last-place", "movement"],
  },
  {
    standardName: "Coach",
    displayName: "教练",
    type: "mainMove",
    abilityText: "和 Coach 同格的所有选手 main move +1，包括 Coach 自己。",
    abilityHooks: ["modifyMainMove"],
    implementationKey: "same_space_main_move_plus_one",
    tags: ["standard", "phase-2-active", "sharing", "main-move"],
  },
  {
    standardName: "Copycat",
    displayName: "模仿猫",
    type: "copy",
    abilityText: "持续拥有当前 lead 选手的能力；多人并列 lead 时选择一个；不复制 before race 能力；冲突时原能力优先。",
    abilityHooks: ["beforeMainMove", "afterRoll", "modifyMainMove", "replaceMainMove", "duringMove", "afterMove"],
    implementationKey: "copy_lead_racer_power",
    tags: ["standard", "copy", "lead"],
  },
  {
    standardName: "Dicemonger",
    displayName: "骰子商人",
    type: "reaction",
    abilityText: "任意选手每回合可重掷 main move 一次；其他选手使用该重掷时，Dicemonger move 1。",
    abilityHooks: ["afterRoll"],
    implementationKey: "grant_reroll_move_on_use",
    tags: ["standard", "reroll", "movement"],
  },
  {
    standardName: "Duelist",
    displayName: "决斗家",
    type: "reaction",
    abilityText: "任意选手与 Duelist sharing a space 时可发起决斗；双方掷骰，高者 move 2，低者 trip；Duelist 平局胜。",
    abilityHooks: ["onSharedStop"],
    implementationKey: "duel_on_shared_space",
    tags: ["standard", "sharing", "duel", "trip"],
  },
  {
    standardName: "Egg",
    displayName: "鸡蛋",
    type: "copy",
    abilityText: "before race 抽 3 名新选手并选择 1 名，使用 Egg 棋子参赛但获得所选角色能力，包括 before race 能力。",
    abilityHooks: ["beforeRace"],
    implementationKey: "draft_temp_power_before_race",
    tags: ["standard", "before-race", "copy"],
  },
  {
    standardName: "Flip Flop",
    displayName: "人字拖",
    type: "warp",
    abilityText: "main move 可以不掷骰，改为与任意选手交换位置；这是 warp，不算 move，双方同时换位。",
    abilityHooks: ["replaceMainMove"],
    implementationKey: "warp_swap_instead_main_move",
    tags: ["standard", "warp", "swap"],
  },
  {
    standardName: "Genius",
    displayName: "天才",
    type: "prediction",
    abilityText: "main move 前预测本次会掷出的点数；若猜中，完成当前回合后再获得一个回合。",
    abilityHooks: ["beforeMainMove", "afterRoll"],
    implementationKey: "predict_roll_extra_turn",
    tags: ["standard", "prediction", "turn-order"],
  },
  {
    standardName: "Gunk",
    displayName: "黏液",
    type: "mainMove",
    abilityText: "其他选手 main move -1；修改移动值而不是修改骰面。",
    abilityHooks: ["modifyMainMove"],
    implementationKey: "others_main_move_minus_one",
    tags: ["standard", "phase-2-active", "main-move"],
  },
  {
    standardName: "Hare",
    displayName: "野兔",
    type: "mainMove",
    abilityText: "main move +2；但若回合开始时独自在 lead，则跳过 main move。",
    abilityHooks: ["beforeMainMove", "modifyMainMove", "replaceMainMove"],
    implementationKey: "hare_fast_unless_alone_lead",
    tags: ["standard", "phase-2-active", "lead", "main-move"],
  },
  {
    standardName: "Heckler",
    displayName: "起哄者",
    type: "reaction",
    abilityText: "任意选手结束回合时，若距离本回合开始位置不超过 1 格，Heckler move 2；trip 恢复也可触发。",
    abilityHooks: ["afterMove"],
    implementationKey: "move_when_turn_ends_near_start",
    tags: ["standard", "reaction", "movement"],
  },
  {
    standardName: "Huge Baby",
    displayName: "巨婴",
    type: "movement",
    abilityText: "除起点外，其他选手不能停在 Huge Baby 的格子；若本该停在该格，则放到 Huge Baby 后一格，这不是 move。",
    abilityHooks: ["onSharedStop"],
    implementationKey: "prevent_sharing_space_push_behind",
    tags: ["standard", "sharing", "positioning"],
  },
  {
    standardName: "Hypnotist",
    displayName: "催眠师",
    type: "warp",
    abilityText: "main move 前可以选择一名选手 warp 到自己的格子。",
    abilityHooks: ["beforeMainMove"],
    implementationKey: "warp_racer_to_self_before_main",
    tags: ["standard", "warp"],
  },
  {
    standardName: "Inchworm",
    displayName: "尺蠖",
    type: "reaction",
    abilityText: "其他选手 main move 掷出 1 时，该选手跳过本次 move，Inchworm move 1。",
    abilityHooks: ["onOtherRoll"],
    implementationKey: "skip_others_one_roll_move_self",
    tags: ["standard", "roll-one", "movement"],
  },
  {
    standardName: "Lackey",
    displayName: "跟班",
    type: "reaction",
    abilityText: "其他选手 main move 掷出 6 时，Lackey 在对方移动前 move 2。",
    abilityHooks: ["onOtherRoll"],
    implementationKey: "move_two_before_other_six",
    tags: ["standard", "roll-six", "movement"],
  },
  {
    standardName: "Leaptoad",
    displayName: "跳跳蛙",
    type: "movement",
    abilityText: "移动时跳过有其他选手的格子，不把那些格子计入步数。",
    abilityHooks: ["duringMove"],
    implementationKey: "skip_occupied_spaces_while_moving",
    tags: ["standard", "movement", "occupied-space"],
  },
  {
    standardName: "Legs",
    displayName: "长腿",
    type: "mainMove",
    abilityText: "main move 可以不掷骰，改为 move 5；这仍算 main move。",
    abilityHooks: ["replaceMainMove"],
    implementationKey: "main_move_fixed_five_optional",
    tags: ["standard", "phase-2-active", "main-move"],
  },
  {
    standardName: "Lovable Loser",
    displayName: "可爱输家",
    type: "scoring",
    abilityText: "main move 前，若自己独自在 last place，获得 1 个 1 分筹码。",
    abilityHooks: ["beforeMainMove"],
    implementationKey: "gain_point_if_alone_last_before_main",
    tags: ["standard", "scoring", "last-place"],
  },
  {
    standardName: "Magician",
    displayName: "魔术师",
    type: "mainMove",
    abilityText: "main move 最多可重掷两次，必须使用最后一次结果。",
    abilityHooks: ["afterRoll"],
    implementationKey: "reroll_main_move_up_to_two",
    tags: ["standard", "phase-2-active", "reroll", "main-move"],
  },
  {
    standardName: "Mastermind",
    displayName: "幕后大师",
    type: "prediction",
    abilityText: "第一次行动开始时预测本场胜者；若猜中，比赛立即结束，Mastermind 得第 2 名；若预测自己且成真，可同时得第 1 和第 2。",
    abilityHooks: ["beforeMainMove", "afterRace"],
    implementationKey: "predict_winner_finish_second",
    tags: ["standard", "prediction", "scoring"],
  },
  {
    standardName: "M.O.U.T.H.",
    displayName: "大嘴",
    type: "special",
    abilityText: "停在正好有 1 名其他选手的格子时，将该选手移出本场比赛。",
    abilityHooks: ["onSharedStop"],
    implementationKey: "eliminate_single_shared_racer",
    tags: ["standard", "elimination", "sharing"],
  },
  {
    standardName: "Party Animal",
    displayName: "派对动物",
    type: "movement",
    abilityText: "main move 前，所有选手各 move 1 朝向 Party Animal；之后其格子上每有 1 名其他选手，main move +1。",
    abilityHooks: ["beforeMainMove", "modifyMainMove"],
    implementationKey: "pull_all_then_bonus_per_guest",
    tags: ["standard", "movement", "sharing"],
  },
  {
    standardName: "Rocket Scientist",
    displayName: "火箭科学家",
    type: "mainMove",
    abilityText: "main move 掷骰后，可以移动双倍点数；若这样做，自己 trip。",
    abilityHooks: ["afterRoll", "modifyMainMove"],
    implementationKey: "optional_double_roll_then_trip",
    tags: ["standard", "phase-2-active", "main-move", "trip"],
  },
  {
    standardName: "Romantic",
    displayName: "浪漫者",
    type: "reaction",
    abilityText: "任意选手停在恰好有 1 名其他选手的格子时，Romantic move 2；若两个选手一起移动并分别触发，则触发两次。",
    abilityHooks: ["onSharedStop"],
    implementationKey: "move_two_on_pair_stop",
    tags: ["standard", "sharing", "movement"],
  },
  {
    standardName: "Scoocher",
    displayName: "挪挪",
    type: "reaction",
    abilityText: "其他选手的能力发生时，Scoocher move 1。",
    abilityHooks: ["onOtherPower"],
    implementationKey: "move_one_on_other_power",
    tags: ["standard", "reaction", "movement"],
  },
  {
    standardName: "Sisyphus",
    displayName: "西西弗斯",
    type: "scoring",
    abilityText: "before race 获得 4 个 1 分筹码；main move 掷出 6 时，改为 warp 到起点并失去 1 分，然后仍继续自己的 main move。",
    abilityHooks: ["beforeRace", "afterRoll"],
    implementationKey: "points_then_six_warp_start",
    tags: ["standard", "scoring", "warp"],
  },
  {
    standardName: "Skipper",
    displayName: "插队者",
    type: "turnOrder",
    abilityText: "任意选手 main move 掷出 1 时，Skipper 立刻成为下一位行动者；之后从 Skipper 左侧继续 turn order。",
    abilityHooks: ["onOtherRoll", "afterRoll"],
    implementationKey: "take_next_turn_on_roll_one",
    tags: ["standard", "turn-order", "roll-one"],
  },
  {
    standardName: "Stickler",
    displayName: "较真者",
    type: "movement",
    abilityText: "其他选手只能用刚好到终点的移动跨线；若移动超过所需格数，则不能冲线。",
    abilityHooks: ["duringMove", "onFinish"],
    implementationKey: "others_need_exact_finish",
    tags: ["standard", "finish", "movement"],
  },
  {
    standardName: "Suckerfish",
    displayName: "吸盘鱼",
    type: "reaction",
    abilityText: "当同格的其他选手 move 时，Suckerfish 可以 move 到该选手的新位置；若一起冲线，目标名次在前。",
    abilityHooks: ["duringMove", "onFinish"],
    implementationKey: "follow_same_space_mover",
    tags: ["standard", "sharing", "movement"],
  },
  {
    standardName: "Third Wheel",
    displayName: "电灯泡",
    type: "warp",
    abilityText: "main move 前，可以 warp 到任意恰好有 2 名选手的格子；warp 后仍正常 main move。",
    abilityHooks: ["beforeMainMove"],
    implementationKey: "warp_to_exactly_two_before_main",
    tags: ["standard", "warp", "sharing"],
  },
  {
    standardName: "Twin",
    displayName: "双胞胎",
    type: "copy",
    abilityText: "before race 选择上一场获胜角色，使用 Twin 棋子参赛但获得该角色能力，包括 before race 能力。",
    abilityHooks: ["beforeRace"],
    implementationKey: "copy_previous_winner_before_race",
    tags: ["standard", "copy", "before-race"],
  },
] as const satisfies readonly AthleteData[];

export const STANDARD_ATHLETES: Athlete[] = STANDARD_ATHLETE_DATA.map((athlete) => {
  const sourceKey = athlete.standardName
    .toLowerCase()
    .replaceAll(/[^a-z0-9]+/g, "_")
    .replaceAll(/^_|_$/g, "");

  return {
    ...athlete,
    id: `athlete-${sourceKey}`,
    sourceKey: `standard_${sourceKey}`,
    artPrompt: `${athlete.standardName} fantasy racing character`,
  };
}) satisfies Athlete[];

export const STANDARD_ATHLETE_BY_ID = new Map(
  STANDARD_ATHLETES.map((athlete) => [athlete.id, athlete]),
);
