import type { Athlete } from "./types";

type AthleteData = Omit<Athlete, "id" | "sourceKey" | "imagePath" | "artPrompt">;

const STANDARD_ATHLETE_DATA = [
  {
    standardName: "Alchemist",
    displayName: "炼金师",
    type: "mainMove",
    abilityText: "主要移动掷出 1 或 2 时，可以改为前进 4 格。",
    abilityHooks: ["afterRoll", "modifyMainMove"],
    implementationKey: "main_roll_low_becomes_four",
    tags: ["standard", "phase-2-active", "main-move"],
  },
  {
    standardName: "Baba Yaga",
    displayName: "芭芭雅嘎",
    type: "reaction",
    abilityText: "任意选手停在她的格子，或她停在任意选手格子时，使对方绊倒。",
    abilityHooks: ["onSharedStop"],
    implementationKey: "trip_on_shared_stop",
    tags: ["standard", "trip", "sharing"],
  },
  {
    standardName: "Banana",
    displayName: "香蕉",
    type: "reaction",
    abilityText: "任意选手超过她时，使该选手绊倒。",
    abilityHooks: ["onPass"],
    implementationKey: "trip_passing_racer",
    tags: ["standard", "phase-2-active", "trip", "passing"],
  },
  {
    standardName: "Blimp",
    displayName: "飞艇",
    type: "mainMove",
    abilityText: "回合开始时若在第 15 格前，主要移动多前进 3 格；若在第 15 格或之后，少前进 1 格。",
    abilityHooks: ["beforeMainMove", "modifyMainMove"],
    implementationKey: "corner_based_main_move_modifier",
    tags: ["standard", "track-position", "main-move"],
  },
  {
    standardName: "Centaur",
    displayName: "半人马",
    type: "movement",
    abilityText: "当他超过一名选手时，被超过者后退 2 格，最低不低于起点。",
    abilityHooks: ["onPass"],
    implementationKey: "move_passed_racer_back_two",
    tags: ["standard", "passing", "movement"],
  },
  {
    standardName: "Cheerleader",
    displayName: "啦啦队长",
    type: "movement",
    abilityText: "主要移动前，可以让唯一最后一名的选手前进 2 格；若这样做，自己再前进 1 格。",
    abilityHooks: ["beforeMainMove"],
    implementationKey: "cheer_last_place_then_self",
    tags: ["standard", "last-place", "movement"],
  },
  {
    standardName: "Coach",
    displayName: "教练",
    type: "mainMove",
    abilityText: "和教练同格的所有选手，主要移动多前进 1 格，包括教练自己。",
    abilityHooks: ["modifyMainMove"],
    implementationKey: "same_space_main_move_plus_one",
    tags: ["standard", "phase-2-active", "sharing", "main-move"],
  },
  {
    standardName: "Copycat",
    displayName: "模仿猫",
    type: "copy",
    abilityText: "持续拥有当前领先选手的能力；多人并列领先时选择一个；不复制赛前能力；冲突时原能力优先。",
    abilityHooks: ["beforeMainMove", "afterRoll", "modifyMainMove", "replaceMainMove", "duringMove", "afterMove"],
    implementationKey: "copy_lead_racer_power",
    tags: ["standard", "copy", "lead"],
  },
  {
    standardName: "Dicemonger",
    displayName: "骰子商人",
    type: "reaction",
    abilityText: "任意选手每回合可重掷主要移动一次；其他选手使用该重掷时，骰子商人前进 1 格。",
    abilityHooks: ["afterRoll"],
    implementationKey: "grant_reroll_move_on_use",
    tags: ["standard", "reroll", "movement"],
  },
  {
    standardName: "Duelist",
    displayName: "决斗家",
    type: "reaction",
    abilityText: "任意选手与决斗家同格时，可以选择一名同格选手决斗；双方掷骰，点数高者前进 2 格；决斗家平局胜。",
    abilityHooks: ["onSharedStop"],
    implementationKey: "duel_on_shared_space",
    tags: ["standard", "sharing", "duel", "optional"],
  },
  {
    standardName: "Egg",
    displayName: "鸡蛋",
    type: "copy",
    abilityText: "赛前抽取 3 名新选手并选择 1 名，使用鸡蛋棋子参赛但获得所选角色能力，包括赛前能力。",
    abilityHooks: ["beforeRace"],
    implementationKey: "draft_temp_power_before_race",
    tags: ["standard", "before-race", "copy"],
  },
  {
    standardName: "Flip Flop",
    displayName: "人字拖",
    type: "warp",
    abilityText: "主要移动可以不掷骰，改为与任意选手交换位置；这是传送，不算移动，双方同时换位。",
    abilityHooks: ["replaceMainMove"],
    implementationKey: "warp_swap_instead_main_move",
    tags: ["standard", "warp", "swap"],
  },
  {
    standardName: "Genius",
    displayName: "天才",
    type: "prediction",
    abilityText: "主要移动前预测本次会掷出的点数；若猜中，完成当前回合后再获得一个回合。",
    abilityHooks: ["beforeMainMove", "afterRoll"],
    implementationKey: "predict_roll_extra_turn",
    tags: ["standard", "prediction", "turn-order"],
  },
  {
    standardName: "Gunk",
    displayName: "黏液",
    type: "mainMove",
    abilityText: "其他选手的主要移动少前进 1 格；修改移动值而不是骰面。",
    abilityHooks: ["modifyMainMove"],
    implementationKey: "others_main_move_minus_one",
    tags: ["standard", "phase-2-active", "main-move"],
  },
  {
    standardName: "Hare",
    displayName: "野兔",
    type: "mainMove",
    abilityText: "主要移动多前进 2 格；但若回合开始时独自领先，则跳过主要移动。",
    abilityHooks: ["beforeMainMove", "modifyMainMove", "replaceMainMove"],
    implementationKey: "hare_fast_unless_alone_lead",
    tags: ["standard", "phase-2-active", "lead", "main-move"],
  },
  {
    standardName: "Heckler",
    displayName: "起哄者",
    type: "reaction",
    abilityText: "任意选手结束回合时，若距离本回合开始位置不超过 1 格，起哄者前进 2 格；绊倒恢复也可触发。",
    abilityHooks: ["afterMove"],
    implementationKey: "move_when_turn_ends_near_start",
    tags: ["standard", "reaction", "movement"],
  },
  {
    standardName: "Huge Baby",
    displayName: "巨婴",
    type: "movement",
    abilityText: "除起点外，其他选手不能停在巨婴的格子；若本该停在该格，则放到巨婴后方一格，这不是移动。",
    abilityHooks: ["onSharedStop"],
    implementationKey: "prevent_sharing_space_push_behind",
    tags: ["standard", "sharing", "positioning"],
  },
  {
    standardName: "Hypnotist",
    displayName: "催眠师",
    type: "warp",
    abilityText: "主要移动前，可以选择一名选手传送到自己的格子。",
    abilityHooks: ["beforeMainMove"],
    implementationKey: "warp_racer_to_self_before_main",
    tags: ["standard", "warp"],
  },
  {
    standardName: "Inchworm",
    displayName: "尺蠖",
    type: "reaction",
    abilityText: "其他选手主要移动掷出 1 时，该选手跳过本次移动，尺蠖前进 1 格。",
    abilityHooks: ["onOtherRoll"],
    implementationKey: "skip_others_one_roll_move_self",
    tags: ["standard", "roll-one", "movement"],
  },
  {
    standardName: "Lackey",
    displayName: "跟班",
    type: "reaction",
    abilityText: "其他选手主要移动掷出 6 时，跟班在对方移动前前进 2 格。",
    abilityHooks: ["onOtherRoll"],
    implementationKey: "move_two_before_other_six",
    tags: ["standard", "roll-six", "movement"],
  },
  {
    standardName: "Leaptoad",
    displayName: "跳跳蛙",
    type: "movement",
    abilityText: "移动时跳过有其他选手的格子，不把那些格子计入步数。",
    abilityHooks: ["duringMove"],
    implementationKey: "skip_occupied_spaces_while_moving",
    tags: ["standard", "movement", "occupied-space"],
  },
  {
    standardName: "Legs",
    displayName: "长腿",
    type: "mainMove",
    abilityText: "主要移动可以不掷骰，改为前进 5 格；这仍算主要移动。",
    abilityHooks: ["replaceMainMove"],
    implementationKey: "main_move_fixed_five_optional",
    tags: ["standard", "phase-2-active", "main-move"],
  },
  {
    standardName: "Lovable Loser",
    displayName: "可爱输家",
    type: "scoring",
    abilityText: "主要移动前，若自己独自最后一名，获得 1 个 1 分筹码。",
    abilityHooks: ["beforeMainMove"],
    implementationKey: "gain_point_if_alone_last_before_main",
    tags: ["standard", "scoring", "last-place"],
  },
  {
    standardName: "Magician",
    displayName: "魔术师",
    type: "mainMove",
    abilityText: "主要移动最多可重掷一次，必须使用最后一次结果。",
    abilityHooks: ["afterRoll"],
    implementationKey: "reroll_main_move_up_to_two",
    tags: ["standard", "phase-2-active", "reroll", "main-move"],
  },
  {
    standardName: "Mastermind",
    displayName: "幕后大师",
    type: "prediction",
    abilityText: "第一次行动开始时预测本场胜者；若猜中，比赛立即结束，幕后大师获得第 2 名；若预测自己且成真，可同时获得第 1 和第 2 名。",
    abilityHooks: ["beforeMainMove", "afterRace"],
    implementationKey: "predict_winner_finish_second",
    tags: ["standard", "prediction", "scoring"],
  },
  {
    standardName: "M.O.U.T.H.",
    displayName: "大嘴",
    type: "special",
    abilityText: "停在正好有 1 名其他选手的格子时，将该选手移出本场比赛。",
    abilityHooks: ["onSharedStop"],
    implementationKey: "eliminate_single_shared_racer",
    tags: ["standard", "elimination", "sharing"],
  },
  {
    standardName: "Party Animal",
    displayName: "派对动物",
    type: "movement",
    abilityText: "主要移动前，所有选手各向派对动物前进 1 格；之后其格子上每有 1 名其他选手，主要移动多前进 1 格。",
    abilityHooks: ["beforeMainMove", "modifyMainMove"],
    implementationKey: "pull_all_then_bonus_per_guest",
    tags: ["standard", "movement", "sharing"],
  },
  {
    standardName: "Rocket Scientist",
    displayName: "火箭科学家",
    type: "mainMove",
    abilityText: "主要移动掷骰后，可以前进双倍点数；若这样做，自己绊倒。",
    abilityHooks: ["afterRoll", "modifyMainMove"],
    implementationKey: "optional_double_roll_then_trip",
    tags: ["standard", "phase-2-active", "main-move", "trip"],
  },
  {
    standardName: "Romantic",
    displayName: "浪漫者",
    type: "reaction",
    abilityText: "任意选手停在恰好有 1 名其他选手的格子时，浪漫者前进 2 格；若两个选手一起移动并分别触发，则触发两次。",
    abilityHooks: ["onSharedStop"],
    implementationKey: "move_two_on_pair_stop",
    tags: ["standard", "sharing", "movement"],
  },
  {
    standardName: "Scoocher",
    displayName: "挪挪",
    type: "reaction",
    abilityText: "其他选手的能力发生时，挪挪前进 1 格。",
    abilityHooks: ["onOtherPower"],
    implementationKey: "move_one_on_other_power",
    tags: ["standard", "reaction", "movement"],
  },
  {
    standardName: "Sisyphus",
    displayName: "西西弗斯",
    type: "scoring",
    abilityText: "赛前获得 4 个 1 分筹码；主要移动掷出 6 时，改为传送到起点并失去 1 分。",
    abilityHooks: ["beforeRace", "afterRoll"],
    implementationKey: "points_then_six_warp_start",
    tags: ["standard", "scoring", "warp"],
  },
  {
    standardName: "Skipper",
    displayName: "插队者",
    type: "turnOrder",
    abilityText: "任意选手主要移动掷出 1 时，插队者立刻成为下一位行动者；之后从插队者左侧继续行动顺序。",
    abilityHooks: ["onOtherRoll", "afterRoll"],
    implementationKey: "take_next_turn_on_roll_one",
    tags: ["standard", "turn-order", "roll-one"],
  },
  {
    standardName: "Stickler",
    displayName: "较真者",
    type: "movement",
    abilityText: "其他选手只能用刚好到终点的移动跨线；若移动超过所需格数，则不能冲线。",
    abilityHooks: ["duringMove", "onFinish"],
    implementationKey: "others_need_exact_finish",
    tags: ["standard", "finish", "movement"],
  },
  {
    standardName: "Suckerfish",
    displayName: "吸盘鱼",
    type: "reaction",
    abilityText: "当同格的其他选手移动时，吸盘鱼可以跟随到该选手的新位置；若一起冲线，目标名次在吸盘鱼之前。",
    abilityHooks: ["duringMove", "onFinish"],
    implementationKey: "follow_same_space_mover",
    tags: ["standard", "sharing", "movement"],
  },
  {
    standardName: "Third Wheel",
    displayName: "电灯泡",
    type: "warp",
    abilityText: "主要移动前，可以传送到任意恰好有 2 名选手的格子；传送后仍正常进行主要移动。",
    abilityHooks: ["beforeMainMove"],
    implementationKey: "warp_to_exactly_two_before_main",
    tags: ["standard", "warp", "sharing"],
  },
  {
    standardName: "Twin",
    displayName: "双胞胎",
    type: "copy",
    abilityText: "赛前选择上一场获胜角色，使用双胞胎棋子参赛但获得该角色能力，包括赛前能力。",
    abilityHooks: ["beforeRace"],
    implementationKey: "copy_previous_winner_before_race",
    tags: ["standard", "copy", "before-race"],
  },
] as const satisfies readonly AthleteData[];

export const STANDARD_ATHLETES: Athlete[] = STANDARD_ATHLETE_DATA.map((athlete) => {
  const sourceKey = athlete.standardName
    .toLowerCase()
    .replaceAll(/[^a-z0-9]+/g, "_")
    .replaceAll(/^_|_$/g, "");
  const id = `athlete-${sourceKey}`;

  return {
    ...athlete,
    id,
    sourceKey: `standard_${sourceKey}`,
    imagePath: `/racers/${id}.png`,
    artPrompt: `${athlete.standardName} fantasy racing character`,
  };
}) satisfies Athlete[];

export const STANDARD_ATHLETE_BY_ID = new Map(
  STANDARD_ATHLETES.map((athlete) => [athlete.id, athlete]),
);
